### PR TITLE
Master handles invalid request

### PR DESCRIPTION
**Pull request by breyed**
When the master receives an invalid request, such as an unsupported function code, it sends an error response to the slave, which contains the appropriate Modbus exception. This functionality is available to the `ModbusSlaveRequestReceived` event handler.

### CODE REVIEW

**Comment by Maxwe11** [comment]
What if we remove setter?

**Comment by breyed** [comment]
I'm not sure what you mean. Which setter are you referring to?

**Comment by Maxwe11** [comment]
Ops...I've cleaned history of commits, so could you update your fork first.

**Comment by Maxwe11** [comment]
Merged in 69e2497. Please update your fork.

**Pull request closed without merging**
